[migrate]
create-schemas = ["accounts"]
table-name = "accounts._sqlx_migrations"

[macros.table-overrides.'accounts.account']
'account_id' = "crate::AccountId"
'password_hash' = "sqlx::types::Text<password_hash::PasswordHashString>"

[macros.table-overrides.'accounts.session']
'session_token' = "crate::SessionToken"
'account_id' = "crate::AccountId"
