[package]
name = "sqlx-example-postgres-preferred-crates-uses-rust-decimal"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
chrono = "0.4"
rust_decimal = "1"
uuid = "1"

[dependencies.sqlx]
workspace = true
features = ["runtime-tokio", "postgres", "rust_decimal", "chrono", "uuid"]

[lints]
workspace = true
