CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ,

    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,

    password TEXT
);
