[package]
name = "accounts"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true, features = ["postgres", "time", "uuid", "macros", "sqlx-toml"] }
tokio = { version = "1", features = ["rt", "sync"] }

argon2 = { version = "0.5.3", features = ["password-hash"] }
password-hash = { version = "0.5", features = ["std"] }

uuid = "1"
thiserror = "1"
rand = "0.8"

time = "0.3.37"

[dev-dependencies]
sqlx = { workspace = true, features = ["runtime-tokio"] }
