[package]
name = "payments"
version = "0.1.0"
edition = "2021"

[dependencies]
accounts = { path = "../accounts" }

sqlx = { workspace = true, features = ["postgres", "time", "uuid", "rust_decimal", "sqlx-toml"] }

rust_decimal = "1.36.0"

time = "0.3.37"
uuid = "1.12.1"

[dev-dependencies]
sqlx = { workspace = true, features = ["runtime-tokio"] }
