[package]
name = "sqlx-example-postgres-multi-database"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

color-eyre = "0.6.3"
dotenvy = "0.15.7"
tracing-subscriber = "0.3.19"

rust_decimal = "1.36.0"

rand = "0.8.5"

[dependencies.sqlx]
# version = "0.9.0"
workspace = true
features = ["runtime-tokio", "postgres", "migrate", "sqlx-toml"]

[dependencies.accounts]
path = "accounts"
package = "sqlx-example-postgres-multi-database-accounts"

[dependencies.payments]
path = "payments"
package = "sqlx-example-postgres-multi-database-payments"

[lints]
workspace = true
