[package]
name = "axum-multi-tenant"
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
accounts = { path = "accounts" }
payments = { path = "payments" }

tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

sqlx = { path = "../../..", version = "0.8.3", features = ["runtime-tokio", "postgres"] }

axum = { version = "0.8.1", features = ["macros"] }

color-eyre = "0.6.3"
dotenvy = "0.15.7"
tracing-subscriber = "0.3.19"

rust_decimal = "1.36.0"

rand = "0.8.5"

[lints]
workspace = true
